### ISSUE TITLE
Unarchive patmenu

### ISSUE THREAD

**Issue by nandub** [km4ack/patmenu2#15]
@km4ack can you UN-archive `patmenu` repository? I would like to push changes into.  The tool is very useful to me with a full desktop or not.

Keeping with the new name theme, are you going to rename it to patmenu-lite?

73,
de KI5LKF

**Comment by km4ack** [comment]
At this time there is no intention to make the original pat menu active again. Feel free to fork it and use it or mod it in any way. 73, de KM4ACK

**Comment by nandub** [comment]
@km4ack no problem, I figure I ask first before going that route.
