### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by motormayhem** [km4ack/patmenu2#17]
I'm installing on a buster raspberry pi. I'm trying to install a non "pi" user account.

Please wait while files are download
This may take several minutes
Depending on your internet speed

(yad:4170): GLib-CRITICAL **: 12:16:58.026: g_source_remove: assertion 'tag > 0' failed

RMS gateway list download success

**Comment by km4ack** [comment]
The glib critical error should have no negative impact on the installation.
