### ISSUE TITLE
Pat Catalog - GPS Wx Doesn't Work With No GPS Attached

### ISSUE THREAD

**Issue by devildog86** [km4ack/patmenu2#20]
When selecting Pat Catalog --> Wx Reports --> GPS Wx, it appears that if no GPS is attached, Pat closes without providing the countdown bar or sending the request to the Outbox of Pat. The only way I can start Pat back up is to kill it in the the Task Manager.

Every other catalog selection seems to work fine... even the other Wx entries.

At first, I thought it was some upgrade I had run. I have reverted back to a previous RPi version and re-loaded my SD card from a backup and the problem still exists.

I modified the "cat-functions" file under the "WEATHER" block and commented out the following:
BODY="https://forecast.weather.gov/MapClick.php?lat="$LAT"&lon=-"$LON"&unit=0&lg=english&FcstType=text&TextType=1"

In its place, I added a new line using previous requests to query@saildocs.com. Except for the coordinates, the syntax was exactly as what I commented out. Pat still shutdown.

If I think of anything else, I'll add it.

Thanks,
Joel, W4JBB

**Comment by km4ack** [comment]
Code has been added to the dev branch which should stop the GPS weather feature from hanging if no gps is attached.
