### ISSUE TITLE
BaP 3.0.7 - XASTIR Shows "NEEDS_UPDATE" when XASTIR is not Installed

### ISSUE THREAD

**Issue by devildog86** [km4ack/patmenu2#21]
Just upgraded to BaP 3.0.7 this morning. After installing and then running, I noticed that XASTIR shows "NEEDS_UPDATE." I do not have XASTIR installed on my system

Thanks,
Joel, W4JBB

**Comment by km4ack** [comment]
bug report posted in BAP repository. https://github.com/km4ack/pi-build/issues/246
