### ISSUE TITLE
Find Gateways File Paths Hardcoded

### ISSUE THREAD

**Issue by motormayhem** [km4ack/patmenu2#22]
Find gateways was crashing the program when I selected "Download Gateway List".
Issue is in find2 file. The file path to FA-functions is hard coded with the pi username. Since my account is not the default pi account this crashes the program. This is consistent for the rest of the find2 file as well. 

**Is**
--field="Download Gateway List":fbtn 'bash -c "kill -USR1 $YAD_PID; source /home/pi/patmenu2/FA-functions; DOWNLIST"' \

**Should be**
--field="Download Gateway List":fbtn 'bash -c "kill -USR1 $YAD_PID; source /$MYPATH/FA-functions; DOWNLIST"' \

**Comment by km4ack** [comment]
fixed in 2.5.0
