### ISSUE TITLE
some questions and feature request

### ISSUE THREAD

**Issue by lowiess** [km4ack/patmenu2#29]
hi,

I realy like your distribution and for the PI is use in in combination with PiHPSDR for the Hermes lite 2
But i can not get the PTT to work i use the VOX now instead put how can i use ptt the -c option does not seem to work

For the PAT menu there is an ARDOP modem an packet modem, do you consider to add VARA ?

73 Frans PE0F

**Comment by km4ack** [comment]
Unfortunately VARA is windows only software and the developer of VARA will not release the code for Linux. There are some guys working on getting it going on Linux. If that happens, I will see if it is possible to implement in Build a Pi.

**Comment by lowiess** [comment]
Ok, Clear answer, and many thanlks for all your work time and effort you have put in to buils a pi
