### ISSUE TITLE
Check to see if Pat is already open

### ISSUE THREAD

**Issue by HamItUp** [km4ack/patmenu2#31]
patmenu2 opens Pat - Mailbox as part of opening a modem. If I close and then re-open a modem (or a new modem), I get another copy of PAT - Mailbox. Suggest that you check to see if Pat - Mailbox  is already running before opening a new instance.

**Comment by km4ack** [comment]
Since the Pat Mailbox opens in a browser, the app could only check to see if a browser window was open. If we close the browser, it could potentially close a browser window that the user had open for another reason not related to Pat.
