### ISSUE TITLE
patmenu2 looks for pat config in the wrong directory

### ISSUE THREAD

**Issue by karlsaintlucy** [km4ack/patmenu2#35]
Hiya KM4ACK, really enjoying your Raspberry Pi 4 build on YouTube. I'm running into an issue when running setup on patmenu2: it looks like patmenu2 is looking for pat's `config.json` file at `$HOME/.wl2k/config.json`; however, pat v0.12.0 puts the config directory in `$HOME/.config/pat/config.json`, so patmenu2 isn't configuring properly for me. I spoke to N6RDF this morning on a net and he said you were working on upgrading your build guide and I thought you might be interested in my case.

It looks like your current implementation has that `$HOME/.wl2k/config.json` string in `/FA-functions`, `/manage-pat-functions`, `/manage-inbox-functions`, `/.getardoplist-cron`, `/getardoplist`, `/manage-inbox`, `/pat-functions` and `/cat-functions`.

I won't presume to know how to fix this, but one solution might be to take the path to the pat config file as an argv when running setup?

73 de KD2YIX

**Comment by km4ack** [comment]
Sorry I didn't see this sooner. There are two branches for pat menu at the moment. The "master" branch supports older version of pat and the "version12" branch supports version 12 and later. You just need to move to the version12 branch:
```
cd ~/patmenu2
git checkout version12
```
I will be dropping support for older version of Pat (<12) in the near future.

73, de KM4ACK
