### ISSUE TITLE
Stop Modems

### ISSUE THREAD

**Issue by netsecninja** [km4ack/patmenu2#46]
Last couple of BAP versions the "Stop Modems" button in the PAT menu hasn't worked. No indication on screen that it's trying to do anything, and no errors either. Ran all updates via the OS and BAP upgrade, rebooted, same issue.

I have a Mobilinkd as my only modem enabled. I tried running `patmenu2/stop-modems` from command line, but it just sits there and does nothing too, no messages.

Raspbian 11
PAT Menu v2.7.0

**Comment by AFlyTyer** [comment]
I too am seeing the same issue; and if I wait long enough it actually kills my PI 400; My VNC connection is killed and I am no longer able to connect to the PI in any fashion and must do a hard reboot.

**Comment by km4ack** [comment]
Please update to version 2.8.0 and see if you still have this issue.
