### ISSUE TITLE
Manage Pat Menu - PAT Menu 2.10.0 Issues

### ISSUE THREAD

**Issue by Mark-wb8sfy** [km4ack/patmenu2#62]
Under Manage Pat:
Pat Login-Logout menu:  (1)If Cancel is selected, the application does not return to the preceding menu level, Pat Menu disappears and has to be reselected from the Desktop Menu. (2) It does not show current settings so you are not sure what you are changing. 

GPS Grid Update:  If this is selected I get the message "Ruby needed to read GPS..."  I believe that I already had installed Ruby as conky is getting GPS and grid updates.  None the less I allowed ruby to install.  I had intentionally manually entered an incorrect grid square and following the ruby update it corrected the Winlink grid square.  The same issue repeats if I again select the GPS Grid Update.

Manual Grid Update:  Does not display current setting so you are not sure what will be changed.

**Comment by km4ack** [comment]
Thank you for the report! Each issue has been addressed and will be included in the stable release. 

73, de KM4ACK
