### ISSUE TITLE
pat load scripts for port 5000

### ISSUE THREAD

**Issue by SpudGunMan** [km4ack/patmenu2#69]
issue:
browser will not open the 127.0.0.1:5000/ui page
fix:
port is 8080 or needs moved to 5000

see full details here: https://groups.io/g/KM4ACK-Pi/message/9240

**Comment by SpudGunMan** [comment]
issue seen in past could not replicate new build of 3.3.1dev appears to be working as intended aarm64

**Comment by km4ack** [comment]
see this reply https://groups.io/g/KM4ACK-Pi/message/9260
