### ISSUE TITLE
Pat shutdown after update to Pat Menu 2

### ISSUE THREAD

**Issue by wh42933** [km4ack/patmenu2#7]
Jason :
First of all thank you for your hard work and making me a better ham(Tech working towards General)  and programmer. Still trying to learning linux and python.
 Pat menu worked and auto-started before updating to pat menu 2 but after updating it stopped all together. Tried to restart pat with the :
sudo systemctl start pat@pi
sudo systemctl enable pat@pi 
reboot
still no joy everything else flrig and so forth still work,
Again thank you for your hard work don't know if anyone else has experienced this issue..

William Harding
N3VMT

**Comment by km4ack** [comment]
can you start pat from the command line with "pat http"? I suspect you have a corrupt pat config file and it won't start from the command line.

**Comment by wh42933** [comment]
Jason,
Tried that and even re-flashed and rebuilt using b-a-p 2 seemed that got got it fixed. I used a different sd card and all think it may have been a damaged/corrupt card. its working fine now.
Again thanks for your hard work and i enjoy you videos. my setup is on a Pi 3b+ connected to a Yaesu FT-857D. just wish FlRig had more controls to the interface but it get the job done. i may only be a Tech but this is going to lead me to my General soon So i can get on the high bands and really explore the hobby more.
Thanks again 

Bill N3VMT

    On Sunday, June 7, 2020, 11:24:54 AM EDT, KM4ACK <notifications@github.com> wrote:  
 
 


can you start pat from the command line with "pat http"? I suspect you have a corrupt pat config file and it won't start from the command line.

**Comment by km4ack** [comment]
Cool. Glad you have it fixed. The 857 could use some more control in FLRIG. I think it's the radio that limits the amount of control we have instead of the software. Look forward to you getting that general ticket and joining us on the HF side. 73, de KM4ACK

**Comment by km4ack** [comment]
Oh....one more thing. Now that you have everything working, use pat menu to backup your config file. I would also recommend a full image of the good SD card.
