### ISSUE TITLE
Finding Gateways

### ISSUE THREAD

**Issue by DJ2GMS** [km4ack/patmenu2#77]
Just installed Patmenu2 on Linux Mint. 
But cannot find gateways. When I do a search with "Search for Gateway" I am getting no results even when searching in a grid I know there is one. The result list stays blank.
When I want to download the Gatewy list it says Grid square not set in Pat configure but it is set.
When I want to do a GPS Grid Update it says Ruby is not installed when I click install the same message is still popping up.
BTW Jason a really great job what you are doing with showing us how to install all that stuff on Mint. Any plans to include Varac in your series?
TNX es vy 73 de Jens, DJ2GMS

**Comment by frrobert2** [comment]
I had a similar error. You need to install jq on your machine.  jq is like sed for JSON data   It should be in your repository for your disro.

**Comment by eyater** [comment]
I had the same problem as DJ2GMS, and installing jq fixed it for me. Thank you for sharing.

**Comment by DJ2GMS** [comment]
Ok, after installing it from the home directory it worked. Thank you👍
