### ISSUE TITLE
install script (yad): GLib-CRITICAL ... failed

### ISSUE THREAD

**Issue by robertreid** [km4ack/patmenu2#83]
$  git clone https://github.com/km4ack/patmenu2.git $HOME/patmenu2 && bash $HOME/patmenu2/setup
Cloning into '/home/robertreid/patmenu2'...
remote: Enumerating objects: 898, done.
remote: Counting objects: 100% (383/383), done.
remote: Compressing objects: 100% (107/107), done.
remote: Total 898 (delta 301), reused 291 (delta 276), pack-reused 515
Receiving objects: 100% (898/898), 2.99 MiB | 11.08 MiB/s, done.
Resolving deltas: 100% (547/547), done.
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Please wait while we check your internet connection
This may take up to a minute

Please wait while files are download
This may take several minutes
Depending on your internet speed

**(yad:11843): GLib-CRITICAL **: 02:41:50.725: g_source_remove: assertion 'tag > 0' failed**

RMS gateway list download success

**Comment by SpudGunMan** [comment]
This is external to the scripts - yad crashed due to (file corruption?) 

Try running yad alone "#> yad" 

You need to fix that as part of the OS (currently failing to load yad)

**Comment by robertreid** [comment]
$ yad
brings up window with only Cancel and OK buttons
not familiar with this program, probably normal
$ sudo apt-get remove yad
$ sudo apt-get install yad
seems to install properly

$ sudo rm -rvf patmenu2
$ git clone https://github.com/km4ack/patmenu2.git $HOME/patmenu2 && bash $HOME/patmenu2/setup
script runs, YAD window pops upj: Downloading ... This takes ~30 seconds, DO NOT CLOSE THIS window, Doing so will abort the download, progress bar progresses, says download complete
but then script says same:
(yad:29781): GLib-CRITICAL **: 10:57:37.276: g_source_remove: assertion 'tag > 0' failed

launch Pat Menu
updated call sign
Pat Menu looks good, nice design
Settings/Config > updated call sign
quit, reboot
Start/Stop Modem > Start Mobilinkd Modem Bluetooth
scanning for devices ... Mobilinkd TNC 4 detected ... Failed: The Mobilinkd Modem FAILED to Start

$ hcitool scan
finds the TNC4 Mobilinkd bluetooth just fine
$ sudo rfcomm connect /dev/rfcomm0 34:81:F4:AA:B9:C4
Can't create RFCOMM TTY: Address already in use
Reboot
tried again
$ sudo rfcomm connect /dev/rfcomm0 34:81:F4:AA:B9:C4
Connected /dev/rfcomm0 to 34:81:F4:AA:B9:C4 on channel 1
Press CTRL-C for hangup
(runs good, leave terminal window open)
(open another terminal window)
$ java -jar ~/Downloads/YAAC/YAAC.jar
YAAC runs great, interacts with modem well

Reboot, launched Pat Menu, tried to again Start Mobilinkd Modem Bluetooth, same response, found but failed to start

conclusion: 
modem is ok
Pat Menu is not installed correctly because of the yad error during script installation
yad seems to be installed properly
I can't figure out how to resolve this
Pat Menu seems really nice, and appreciate all of km4ack's hard work, hoping to resolve this
